### ISSUE TITLE
PTPDFViewCtrl.setDoc(.init(filePath)) crashes if a non-valid PDF is passed

### ISSUE THREAD

**Issue by samitaha2** [PDFTron/PDFNetLoader#3]
We are having some issues where occasionally we have a bad PDF.  When we call `PTPDFViewCtrl.setDoc`, this causes a crash. How can we gracefully handle this? Is there a way to check if the file is a valid PDF prior to sending it to you guys and experiencing a crash?

**Comment by rbarrpdftron** [comment]
@samitaha2 if the issue is truly file specific, then you would have to submit that ticket to us for further investigation. Either submit here, or here: https://www.pdftron.com/form/request/

Otherwise, I suspect you are not calling PDFNet.Initialize() first, before using any other parts of our API.
